name: CI Deploy

on:
  push:
    branches:
      - main
    tags:

env:
  IMG: docker.pkg.github.com/kokuwaio/docker-rauc/rauc

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kokuwaio/docker-rauc/rauc
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          registry: docker.pkg.github.com
      - name: Publish Tag to Registry
        if: contains(github.ref, 'refs/tags/v')
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kokuwaio/docker-rauc/rauc
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tagging: true
          registry: docker.pkg.github.com